services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: e-commerce-project
    restart: always
    ports:
      - "4002:4002"
    depends_on:
      - postgres
      - redis
    env_file:
      - ../../.env
      - ../../.env.development
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: e-commerce-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: e-commerce-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../../.env
      - ../../.env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
