version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    container_name: e-commerce-prod
    restart: always
    expose:
      - "4002"
    depends_on:
      - postgres
      - redis
    env_file:
      - ../../.env.production
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: e-commerce-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: e-commerce-redis-prod
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: e-commerce-db-prod
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pass
      POSTGRES_DB: e-commerce
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data_prod:

networks:
  app_network:
